llm:
  openai:
    provider: "openai"
    model_name: "o4-mini"
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
  ollama:
    provider: "ollama"
    model_name: "llama3-groq-tool-use:latest"
  gemini:
    provider: "gemini"
    model_name: "gemini-2.5-flash"
